### PR TITLE
Add gouttelette dependency to setup.cfg

### PR DESCRIPTION
**Pull request by GomathiselviS**
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by alinabuzachis** [comment]
It doesn't seem finding now😳

```
2023-01-10 21:40:45.285549 \| controller \| FileNotFoundError: [Errno 2] No such file or directory: '/workspace/src/github.com/ansible-collections/vmware_rest_code_generator/.tox/generate/lib/python3.11/site-packages/gouttelette/api_specifications/vmware_rest/7.0.2/vcenter.json'
670

<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">
```

**Comment by GomathiselviS** [comment]
> It doesn't seem finding nowflushed
> 
> ```
> 2023-01-10 21:40:45.285549 \| controller \| FileNotFoundError: [Errno 2] No such file or directory: '/workspace/src/github.com/ansible-collections/vmware_rest_code_generator/.tox/generate/lib/python3.11/site-packages/gouttelette/api_specifications/vmware_rest/7.0.2/vcenter.json'
> 670
> 
> <br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">
> ```

[This PR](https://github.com/ansible-collections/gouttelette/pull/37) should fix this issue. Thanks for pointing it out.

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Review by alinabuzachis — COMMENTED** [review]
I guess ` __pycache__ ` folder can be removed.

**Review by alinabuzachis — APPROVED** [review]

**Pull request merged**
